directories:
  output: release
  buildResources: build
appId: com.yourcompany.fuelapp
publish:
  provider: github
  owner: Yazi939
  repo: Bunker-final-product
files:
  - filter:
      - dist/**/*
      - main.cjs
      - preload.cjs
      - package.json
extraResources:
  - from: src
    to: app/src
    filter:
      - '**/*'
  - from: build/database
    to: app/build/database
    filter:
      - '**/*'
win:
  target: nsis
  icon: public/bunker-logo.jpg
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
asar: false
compression: store
npmRebuild: false
buildDependenciesFromSource: false
nodeGypRebuild: false
electronVersion: 28.3.3
